CREATE TABLE IF NOT EXISTS randomuser_kudu(
        login_uuid string,
        login_username string,
        login_password string,
        login_salt string,
        login_md5 string,
        login_sha1 string,
        login_sha256 string,
        gender string,
        name_title string,
        name_first string,
        name_last string,
        location_street string,
        location_city string,
        location_state string,
        location_postcode string,
        location_coordinates_latitude string,
        location_coordinates_longitude string,
        location_timezone_offset string,
        location_timezone_description string,
        email string,
        dob_date string,
        dob_age string,
        registered_date string,
        registered_age string,
        phone string,
        cell string,
        id_name string,
        id_value string,
        picture_large string,
        picture_medium string,
        picture_thumbnail string,
        nat string,
        PRIMARY KEY (login_uuid))
    STORED AS KUDU
    TBLPROPERTIES (
      'kudu.master_addresses' = 'quickstart.cloudera:7051',
      'kudu.num_tablet_replicas' = '1'
    )
